name: Industry Report Bot

on:
  schedule:
    - cron: '*/30 0-10,23 * * *'
  workflow_dispatch:

permissions:
  contents: write # ⭐️ 깃허브에 수첩을 저장할 수 있는 권한 부여!

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4

      - name: Run bot
        run: python bot.py

      - name: Save memory
        run: |
          git config user.name "GitHub Action Bot"
          git config user.email "action@github.com"
          git add last_title.txt
          git commit -m "Update last report" || echo "새로운 리포트 없음"
          git push
