name: Industry Report Bot

on:
  schedule:
    # 한국 시간 기준 오전 8시 ~ 오후 7시 사이 30분마다 작동하게 수정했습니다.
    - cron: '*/30 0-10,23 * * *' 
  workflow_dispatch: # 우리가 직접 실행 버튼을 누를 수 있게 해줍니다.

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4

      - name: Run bot
        run: python bot.py
